Feature/fuku/check
vantan-project/wakashachiAppFront pull request #7
Opened 2024-12-20 04:13 UTC by Fukushinaharuto

<img width="1470" alt="スクリーンショット 2024-12-20 12 56 47" src="https://github.com/user-attachments/assets/728f37e0-4024-4761-a956-5e121fd783e7" />
<img width="1470" alt="スクリーンショット 2024-12-20 12 56 43" src="https://github.com/user-attachments/assets/f646df07-b577-4ffb-85af-5342a95559f8" />

1. レイアウトは完成したけど、実際に使う環境がないから、機能のテストはできてません。

2024-12-21 08:22 UTC, Kate0418 requested changes
## 惜しい

2024-12-21 08:22 UTC, Kate0418 commented on next-app/src/components/layout/SearchBox.tsx
> +            <Image
普通にこれでいいよ
```ts
placeholder={placeholder}
```

2024-12-23 04:14 UTC, Fukushinaharuto commented on next-app/src/components/layout/SearchBox.tsx
> +            <Image
了解

2025-01-03 20:05 UTC, Kate0418 approved these changes
# ⭕️

2025-01-08 02:40 UTC, merged